# Generated by Django 5.0.6 on 2024-07-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_add_job_author_alter_add_job_comapany_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='comapany_name',
            field=models.CharField(max_length=100),
        ),
    ]
